run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - bodyclose # checks whether HTTP response body is closed successfully
    - unused # checks for unused constants, variables, functions and types
    - errcheck # checking for unchecked errors, these unchecked errors can be critical bugs in some cases
    - typecheck # like the front-end of a Go compiler, parses and type-checks Go code
    - usestdlibvars # detects the possibility to use variables/constants from the Go standard library
    - goconst # finds repeated strings that could be replaced by a constant
    - perfsprint # checks that fmt.Sprintf can be replaced with a faster alternative
    - gosimple # specializes in simplifying a code
    - gosec # inspects source code for security problems

linters-settings:
  goconst:
    ignore-strings: '%s=%s'
  perfsprint:
    # Optimizes into strings concatenation.
    # Default: true
    strconcat: false
    
issues:
  max-same-issues: 50
