// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// BucketStreamer is an autogenerated mock type for the BucketStreamer type
type BucketStreamer struct {
	mock.Mock
}

// Construct provides a mock function with given fields: Bucket
func (_m *BucketStreamer) Construct(Bucket string) {
	_m.Called(Bucket)
}

// ReadStreaming provides a mock function with given fields: ctx, path
func (_m *BucketStreamer) ReadStreaming(ctx context.Context, path string) (io.ReadCloser, int64, error) {
	ret := _m.Called(ctx, path)

	if len(ret) == 0 {
		panic("no return value specified for ReadStreaming")
	}

	var r0 io.ReadCloser
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (io.ReadCloser, int64, error)); ok {
		return rf(ctx, path)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) io.ReadCloser); ok {
		r0 = rf(ctx, path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) int64); ok {
		r1 = rf(ctx, path)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = rf(ctx, path)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewBucketStreamer creates a new instance of BucketStreamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBucketStreamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *BucketStreamer {
	mock := &BucketStreamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
