name: Merged
run-name: Merge - "${{ github.sha }}"
on:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24.0
    steps:
      - uses: actions/checkout@v4
        with:
          - uses: actions/checkout@v4
            with:
              path: 'goUtils' # TODO: ?
              #token: '' # TODO: FIX
              #ssh-key: '' # TODO:?
              # Relative path under $GITHUB_WORKSPACE to place the repository
      - name: install dependencies
        run: go install github.com/vektra/mockery/v3@v3.2.2
      - name: generate-mocks
        run: go generate ./...
        working-directory: goUtils
      - name: vet
        run: go vet ./...
        working-directory: goUtils
      - name: test
        run: go test ./...
        working-directory: goUtils
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.64.5'
          working-directory: goUtils