name: PR Commit
run-name: PR - ${{ github.ref }} - "${{ github.sha }}"
on:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: golang:1.24.0
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'goUtils' # TODO: ?
          #token: '' # TODO: FIX
          #ssh-key: '' # TODO:?
          # Relative path under $GITHUB_WORKSPACE to place the repository
      - name: vet
        run: go vet ./...
        working-directory: goUtils
      - name: test
        run: go test ./...
        working-directory: goUtils
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: 'v1.64.5'
          working-directory: goUtils
